# Generated by Django 3.2.19 on 2023-06-29 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="end_booking_sate",
            new_name="end_booking_date",
        ),
    ]
